// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/index').default>>>>
    }
    '/mcp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/mcp/index.post').default>>>>
    }
    '/v1/createNewProject': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/createNewProject.post').default>>>>
    }
    '/v1/getAllProjects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getAllProjects.get').default>>>>
    }
    '/v1/getApiBlueprints': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getApiBlueprints.get').default>>>>
    }
    '/v1/getCloudCredentials': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getCloudCredentials.get').default>>>>
    }
    '/v1/getMcpKey': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getMcpKey.get').default>>>>
    }
    '/v1/getProjectActions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getProjectActions.get').default>>>>
    }
    '/v1/getProjectDatabases': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getProjectDatabases.get').default>>>>
    }
    '/v1/getProjectDeployments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getProjectDeployments.get').default>>>>
    }
    '/v1/getProjectDetails': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getProjectDetails.get').default>>>>
    }
    '/v1/getProjectFileContent': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getProjectFileContent.get').default>>>>
    }
    '/v1/getProjectFiles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/getProjectFiles.get').default>>>>
    }
    '/v1/updateCloudCredentials': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/v1/updateCloudCredentials.post').default>>>>
    }
    '/webhooks/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/webhooks/signup/index.post').default>>>>
    }
    '/webhooks/testRedisJob': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/webhooks/testRedisJob/index.post').default>>>>
    }
  }
}
export {}